transcription/urls.py
from django.conf.urls import patterns, url

import settings

pattern_args = ['',
                url('^transcribe$',
                    'transcription.views.transcribe',
                    name='transcribe'),

                url('^open_annotations$',
                    'transcription.views.open_annions',
                    name='open_annions'),

                url('^static/(?P<path>.*)$',
                    'django.views.static.serve'),

                url('^data/recs/(?P<path>.*)$',
                    'django.views.static.serve',
                    {'document_root': settings.CONVERSATION_DIR}),

                url('^finished$',
                    'transcription.views.finished',
                    name="finished"),

                url('^import$',
                    'transcription.views.import_dialogues',
                    name="import_dialogues"),

                url('^delete$',
                    'transcription.views.delete_list',
                    name="delete_dialogues"),

                url('^stats$',
                    'transcription.views.dialogue_stats',
                    name="dialogue_stats"),
                ]

if settings.DEBUG:
    pattern_args.append(url(r'^test-view$',
                            'transcription.views.temp_test',
                            name="test_view"))

# Only when using Crowdflower:
if settings.USE_CF:
    cf_pattern_args = [url('^create-jobs$',
                           'transcription.views.create_job_view',
                           name="create_jobs"),
                       url('^delete-jobs$',
                           'transcription.views.delete_job_view',
                           name="delete_jobs"),
                       url('^collect-reports$',
                           'transcription.views.collect_reports',
                           name="collect_reports"),
                       url('^fill-in-worker-ids$',
                           'transcription.views.fill_in_worker_ids',
                           name="fill_in_worker_ids"),
                       ]
    pattern_args.extend(cf_pattern_args)
    if settings.USE_WEBHOOKS:
        cf_pattern_args = [url('^log-work$',
                               'transcription.views.log_work',
                               name="log_work"),
                           url('^fire-hooks$',
                               'transcription.views.fire_hooks',
                               name="fire_hooks"),
                           url('^reuse-worklogs$',
                               'transcription.views.reuse_worklogs',
                               name="reuse_worklogs"),
                           ]
        pattern_args.extend(cf_pattern_args)

# Displaying the home page is the default.
pattern_args.append(url(r'^',
                        'transcription.views.home',
                        name='home'))

urlpatterns = patterns(*pattern_args)

trs_site/urls.py
from django.conf.urls.defaults import patterns, include, url

import settings

from django.contrib import admin
admin.autodiscover()

pattern_args = [
    url(r'^admin/', include(admin.site.urls), name="admin"),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', name='login'),
]

_file_email_backend = 'django.core.mail.backends.filebased.EmailBackend'
if settings.EMAIL_BACKEND == _file_email_backend:
    pattern_args.append(
        url(r'^accounts/password_reset/done/$',
            'trs_site.views.password_reset_done',
            name='password_reset_done'))

pattern_args.extend((
    url('^accounts/', include('django.contrib.auth.urls')),
    url(r'^media/(?P<path>.*)$',
        'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$',
        'django.views.static.serve',
        {'document_root': settings.STATIC_ROOT}),
    url(r'^', include('transcription.urls'))))

urlpatterns = patterns('', *pattern_args)

transcription/forms.py
#!/usr/bin/python
# -*- coding: UTF-8 -*-

from __future__ import unicode_literals

import os
import re

from django import forms
from django.utils.datastructures import SortedDict

from crowdflower import default_job_cml_path, price_class_handler
from form_fields import DatetimeField, ListField
from models import Dialogue
import settings


class CustomFieldsForm(forms.Form):
    def __init__(self, fields, data=None):
        super(CustomFieldsForm, self).__init__(data)
        self.fields.update(fields)


class TranscriptionForm(forms.Form):
    if 'info_provided' in settings.EXTRA_QUESTIONS:
        info_provided = forms.BooleanField(required=False)
    if 'quality' in settings.EXTRA_QUESTIONS:
        quality = forms.CharField()
    if 'accent' in settings.EXTRA_QUESTIONS:
        accent = forms.CharField()
        accent_name = forms.CharField(required=False)
    if 'offensive' in settings.EXTRA_QUESTIONS:
        offensive = forms.BooleanField(required=False)
    notes = forms.CharField(required=False)

    def __init__(self, *args, **kwargs):
        turn_dicts = kwargs.pop('turn_dicts', None)
        trs_required = kwargs.pop('trs_required', True)
        if turn_dicts is None:
            turn_dicts = tuple()
        cid = kwargs.pop('cid', None)
        if args:
            data = args[0]
        else:
            data = kwargs.get('data', None)
        super(TranscriptionForm, self).__init__(*args, **kwargs)

        self.fields['cid'] = forms.CharField(widget=forms.HiddenInput(),
                                             initial=cid)

        # FIXME These variable-number data are not regenerated currently.
        # Recover transcriptions.
        if 'asr' in settings.TASKS:
            for tpt_turn_num, turn_dict in enumerate(turn_dicts, start=1):
                if not turn_dict['has_rec']:
                    continue
                self.fields['trs_{0}'.format(tpt_turn_num)] = forms.CharField(
                    widget=forms.Textarea(
                        attrs={'style': 'width: 90%', 'rows': '3'}),
                    label=tpt_turn_num,
                    required=trs_required)

        # Recover semantic annotations.
        if 'slu' in settings.TASKS:
            if data is not None:
                checklist = filter(lambda item: item[0].startswith('check'),
                                   data.iteritems())
                for tpt_turn_num, turn_dict in enumerate(turn_dicts, start=1):
                    if not turn_dict['has_rec']:
                        continue
                    sem_prefix = 'sludai_{0}_'.format(tpt_turn_num)
                    dat_prefix = 'newdat_{0}_'.format(tpt_turn_num)
                    sem_trss = filter(
                        lambda item: item[0].startswith(sem_prefix),
                        data.iteritems())
                    for trs_name, text in sem_trss:
                        # FIXME This is weird, using the checkbox widget for
                        # a text input field. Why is this so?
                        self.fields[trs_name] = forms.CharField(
                            widget=forms.CheckboxInput())
                    newdat_trss = filter(
                        lambda item: item[0].startswith(dat_prefix),
                        data.iteritems())
                    for trs_name, text in newdat_trss:
                        if text != '':
                            coords = trs_name[len('newdat_'):]
                            check_name = 'check_{coo}'.format(coo=coords)
                            if check_name in checklist:
                                self.fields['newdat_{0}'.format(coords)] = (
                                    forms.CharField(widget=forms.Select()))
                                self.fields['slot_{0}'.format(coords)] = (
                                    forms.CharField(widget=forms.Select()))
                                self.fields['value_{0}'.format(coords)] = (
                                    forms.CharField(widget=forms.Select()))

    def __unicode__(self):
        import pprint
        return pprint.pformat(self.fields, depth=3)

    def __repr__(self):
        return self.__unicode__()

    def __str__(self):
        return self.__unicode__()


class DateRangeForm(forms.Form):
    dt_from = DatetimeField(label='from after (excl.)', required=False)
    dt_to = DatetimeField(label='until (incl.)', required=False)


class FileListForm(CustomFieldsForm):

    def __init__(self, data=None):
        dg_lists = sorted(Dialogue.objects
                          .values_list('list_filename', flat=True).distinct())
        dg_flist_tups = [(list_fname, list_fname) for list_fname in dg_lists]
        fields = {'file_list': forms.ChoiceField(choices=dg_flist_tups)}
        super(FileListForm, self).__init__(fields, data)


if settings.USE_CF:
    class WorkLogsForm(forms.Form):
        logs_list_path = forms.FilePathField(
            path=settings.LISTS_DIR,
            label="Path to the worklogs list file",
            help_text=('Select the file that lists paths towards worklog '
                       'files that should be reused.'))


    class CreateJobForm(forms.Form):
        """A form for creating Crowdflower jobs."""

        class CountriesField(ListField):
            """Form field for entering country codes."""
            def validate(self, value):
                "Check if value consists only of two-letter codes."
                # Use the parent's handling of required fields, etc.
                super(CreateJobForm.CountriesField, self).validate(value)
                wrong_codes = set()
                for code in value:
                    if len(code) != 2 or not code.isupper():
                        wrong_codes.add(code)
                if wrong_codes:
                    codes_list = ', '.join('"{code}"'.format(code=code)
                                           for code in sorted(wrong_codes))
                    msg = ('Following are definitely not valid country codes: '
                           '{codes}.').format(codes=codes_list)
                    raise forms.ValidationError(msg)

        class PricesField(forms.Field):
            """Form field for entering a list of integers."""
            def to_python(self, value):
                "Normalize data to a list of integers."
                # Return None if no input was given.
                if not value:
                    return list()

                # Otherwise, check all input values whether they can be coerced
                # to ints.
                string_list = set(map(unicode.strip, value.split(',')))
                wrong_ints = set()
                good_ints = set()
                for int_str in string_list:
                    try:
                        good_ints.add(int(int_str))
                    except ValueError:
                        wrong_ints.add(int_str)
                if wrong_ints:
                    ints_list = ', '.join('"{int_}"'.format(int_=int_)
                                          for int_ in wrong_ints)
                    msg = ('Following are not valid integers: {ints}.'
                           .format(ints=ints_list))
                    raise forms.ValidationError(msg)
                else:
                    return list(sorted(good_ints))

        # Constants.
        default_countries = ",".join(("AU", "CA", "GB", "IE", "IM", "NZ",
                                      "US"))
        default_title = 'Dialogue transcription – price level {price_tenth}'
        default_instructions = re.sub(' +', ' ', """\
            Please, write down what is said in the provided recordings. The
            recordings capture a dialogue between a human and a computer. The
            computer utterances are known, so only the human's utterances need
            to be transcribed.""").strip().replace('\n ', '\n')
        inputWidth = len(default_title)
        fixedWidthTextInput = forms.TextInput(attrs={'size': inputWidth})

        # Fields.
        cents_per_unit = PricesField(
            initial='5, 10, 20, 30',
            widget=fixedWidthTextInput,
            help_text=('Specify desired price per dialogue in cents. This can '
                       'be a comma-separated list of integers. A job will be '
                       'created for each price specified here.'))
        store_job_id = forms.BooleanField(
            initial=True,
            label='Store job ID',
            help_text=('Should job IDs be written to a job ID list file? '
                       '(Leave this checked if you want to upload dialogues '
                       'for this job.)'),
            required=False)
        job_cml_path = forms.FilePathField(
            path=os.path.dirname(default_job_cml_path),
            match='\.cml$',
            initial=default_job_cml_path,
            label="Path to the job CML file",
            help_text=('Select the file that defines the body of the '
                       'Crowdflower unit.\n'
                       'If you see no choices here, you might need to run '
                       'the scripts/setup_script.py script yet.'))
        judgments_per_unit = forms.IntegerField(
            initial=1,
            widget=fixedWidthTextInput,
            help_text='How many times do you want each dialogue transcribed?')
        units_per_assignment = forms.IntegerField(
            initial=2,
            widget=fixedWidthTextInput,
            help_text='How many dialogues in a HIT?')
        pages_per_assignment = forms.IntegerField(
            initial=1,
            widget=fixedWidthTextInput,
            help_text='How many visual pages to split each HIT into?')
        gold_per_assignment = forms.IntegerField(
            initial=1,
            widget=fixedWidthTextInput,
            help_text='How many gold dialogues per HIT?')
        title = forms.CharField(
            initial=default_title, widget=fixedWidthTextInput,

transcription/templates/er/transcribe.html
{% extends "base.html" %}

{% block head %}
<script src="http://vystadial.ms.mff.cuni.cz/apps/transcription/media/js/easyXDM.min.js" type="text/javascript"></script>
<script type="text/javascript">
<!--
	var socket = new easyXDM.Socket({
			onReady:	function(){
					socket.postMessage(document.body.scrollHeight);
		 }
	});
//-->
</script>
<link href="{{ MEDIA_URL }}css/jquery-ui.css" rel="stylesheet" type="text/css"/>
<style type="text/css">
hr {
	margin: 20px;
}

form label {
		vertical-align: top;
		display: block;
}

div#ins, div#dg {
	display: inline-block;
}

div#ins {
	margin: 1em 2ex 0ex 2ex;
	min-width: 45em;
	max-width: 55em;
}

div#dg {
	width: 60em;
	max-width: 60em;
}

#id_notes {
	margin-left: auto;
	margin-right: auto;
}

input#ins-hide {
	float: right;
	margin-right: 1em;
}

.quote {
	margin-left: auto;
	margin-right: auto;
	width: 80%;
}

.no {
	color: red;
	font-weight: bold;
}

.yes {
	color: green;
	font-weight: bold;
}

.centering {
	padding: 0pt;
	text-align: center;
}

ul.errorlist {
		color: red;
		display:block;
}

div#task {
	xborder: 1px solid red;
	xbackground-color: #FFCCCC;
	margin-top: 20px;
	margin: 5px;
	padding: 5px;
}

div#goal {
	border: 1px solid yellow;
	background-color: #FFFFCC;
	margin-top: 20px;
	margin: 5px;
	padding: 5px;
}

p.tasktext {
	font-weight: bold;
	color: red;
	padding-top: 5px !important;
}

p.goaltext, #task p {
	padding: 0px;
	margin: 0px;
}

.speaker {
	position: relative;
	left: -1em;
	font-weight: bold;
}


/* Tables */
table.booktabs	{
	margin-top: 1em;
	margin-bottom: 2em;
	border-bottom: 1.5pt solid;
	border-top: 1.5pt solid;
	border-spacing: 1em;
	border-collapse: collapse;
}

td, th {
	padding: 5px;
}

table.booktabs td + td, table.booktabs th + th
{
	padding-left: 2em;
}

table.booktabs tr:first-child {
	border-bottom: 1pt solid;
}

table.booktabs.noheader tr:first-child {
	border-bottom: inherit;
}

form li {
	list-style-type: none;
	padding-top: 10px;
}

p.system { color: blue; }
p.user { color: orange; }

.errors {
		background-color: red;
		color: white;
}

#submit {
	width: 120px;
	height: 50px;
	font-weight: bold;
}

</style>
<script src="{{ MEDIA_URL }}js/jquery.js"></script>
<script src="{{ MEDIA_URL }}js/jquery.multi-open-accordion.js"></script>
<script src="{{ MEDIA_URL }}js/jquery-ui.min.js"></script>
<script src="{{ MEDIA_URL }}js/jquery.jplayer.min.js"></script>
<script type="text/javascript">
		String.prototype.endsWith = function(suffix) {
				return this.indexOf(suffix, this.length - suffix.length) !== -1;
		};
		var curr_btnid = "";

		var beenPlaying = false;

	function getPlayer(pid) {
			var obj = document.getElementById(pid);
			if (obj.doPlay) return obj;
			for(i=0; i<obj.childNodes.length; i++) {
					var child = obj.childNodes[i];
					if (child.tagName == "EMBED") return child;
			}
	}

	function NextPhase() {
			var PrevIndex = $('div .current');
			var NextIndex = PrevIndex.next().next();
			PrevIndex.removeClass("current");
			NextIndex.addClass("current");
			//NextIndex.click();

			NextIndex.removeClass("ui-state-disabled");
			if(!NextIndex.hasClass("ui-state-active"))
					NextIndex.click();
	}

	function PlayerStopped() {
			if(beenPlaying) {
					beenPlaying = false;
					$('#' + curr_btnid).text("Play");

					NextPhase();
			}
	}

	function PlayerPlaying() {
			beenPlaying = true;
	}

	function init_player(name) {
			var player = getPlayer(name);
			var init = function() { init_player(name); }
			if (!player || !player.attachHandler) setTimeout(init, 100); // Wait for load
			else {
					player.attachHandler("PLAYER_PLAYING", "PlayerPlaying", "STOPPED");
					player.attachHandler("PLAYER_STOPPED", "PlayerStopped", "STOPPED");
					//window.TinyWav = new TinyWav('TinyWavBlock', 0.01);
			}
	}

	function deinit_player(name) {
			var player = getPlayer(name);
			var init = function() { init_player(name); }
			if (!player || !player.attachHandler) setTimeout(init, 100); // Wait for load
			else {
					player.removeHandler(PlayerStopped);
			}
	}

	var accordion, hideButton, insAreShown = true;

	// Callback function called when the instructions have been hidden.
	function insHidden() {
		insAreShown = false;
		hideButton.value = "Show instructions";
		hideButton.disabled = false;
	}

	// Callback function called when the instructions have been shown.
	function insShown() {
		insAreShown = true;
		hideButton.value = "Hide instructions";
		hideButton.disabled = false;
	}

	$(document).ready(function() {
			accordion = $("#phases").multiAccordion({active: 0});
			$("#accent_spec").slideUp();

			$("#player").jPlayer( {
					swfPath: "{{ MEDIA_URL }}flash/",
					supplied: "wav",
					ended: function() {
							PlayerStopped();
					}
			});

			$("#turn_1").removeClass("ui-state-disabled");

			var native_accent = document.getElementById("id_accent_native");
			var other_accent = document.getElementById("id_accent_other");
			var accent_name = document.getElementById("id_accent_name");
			$("#id_accent_native").change(function() {
				if(native_accent.checked)
				{
					$("#accent_spec").slideUp();
				}
			});
			$("#id_accent_other").change(function() {
				if(other_accent.checked)
				{
					$("#accent_spec").slideDown();
				}
			});

			$("#submit").click(function() {
					// Check that all fields (text areas) are filled in.
					var res = 1;
					var fields = document.getElementsByTagName("textarea");
					for(var fldIdx = 0; fldIdx < fields.length; fldIdx++)
					{
						field = fields[fldIdx];
						if(field.id === "id_notes")
						{
							continue;
						}
						if(fields[fldIdx].value.search(/\w/) === -1)
						{
							res = 0;
							break;
						}
					}

					if(res !== 1) {
						msg = "Please fill in all the input fields.\n";
						msg += "In case you heard just silence, type \"(sil)\" ";
						msg += "into the corresponding field.\n";
						msg += "See Instructions for transcription of other ";
						msg += "non-speech sounds.";
						alert(msg);
						return false;
					}
					
					if(other_accent.checked && accent_name.value.search(/\w/) === -1)
					{
						msg = "You say the speaker had a non-native English accent.\n";
						msg += "Please, specify what accent you think he/she had.";
						alert(msg);
						return false;
					}
					return true;
			});

			hideButton = document.getElementById("ins-hide");
			$("input#ins-hide").click(function() {
				hideButton.disabled = true;
				if(insAreShown)
				{
					$("div#ins-inner").slideUp("fast", "swing", insHidden);
				}
				else
				{
					$("div#ins-inner").slideDown("fast", "swing", insShown);
				}
			});
	});

	function play_now(btnid, phase, f) {
			curr_btnid = btnid;
			$(".current").removeClass("current");
			$("#" + phase).addClass("current");
			try{
					PlayerPlaying();
					$('#' + btnid).text("Playing...");
					$("#player").jPlayer("setMedia", {wav: f}).jPlayer("play");
			} catch(E){
					alert(E);
			}
	}

	function pseudo_play_now(btnid, phase, f) {
			curr_btnid = btnid;
			$(".current").removeClass("current");
			$("#" + phase).addClass("current");
			NextPhase();
	}
</script>

{% endblock head %}


{% block content %}


<span>
	<div id="ins">
		<div class="centering">
			<img src="{{ MEDIA_URL }}img/logo_ufal_73_transparent.png" width="91" 
			height="73" />
		</div>

		<h2>Instructions
			<input type="button" id="ins-hide" value="Hide instructions"></input>
		</h2>
		
		<div id="ins-inner">
			<p>
			The recordings and input fields will be enabled gradually, each time you 
			finish listening to the previous recording. You can replay each sound any 
			time later.
			</p>

			<h3>Ortography</h3>
			<p>
			Please, try to avoid spelling errors. Punctuation and capitalisation 
			generally do not matter. The exception is with acronyms &ndash; 
			please transcribe acronyms in uppercase letters.
			</p>

			<h3>Numerals</h3>
			<p>
			Please, do <em>not</em> use numbers to transcribe numerals; 
			spell them out:
			<div class="quote">
				<table>
					<tr>
						<td>53</td>
						<td class="no">NO</td>
					<tr>
						<td>fifty three</td>
						<td class="yes">YES</td>
					</tr>
				</table>
			</div>
			</p>

			<h3>Incomplete Words</h3>
			<p>
			If a word is pronounced incomplete, put &lsquo;-&rsquo; (dash) before 
			or after the pronounced part of the word.
			</p>
			<p>
			<strong>Examples:</strong> incomp- -eech -crastinat-
			</p>

			<h3>Non-speech Sounds</h3>
			<p>
			For non-speech sounds, you can transcribe them using the following symbols:
			</p>
	
			<table class="booktabs">
				<tr>
					<th>symbol</th>
					<th>meaning</th>
				</tr>
				<tr>
					<td>(breath)</td>
					<td>the sound of breathing, sniffing etc.</td>
				</tr>
				<tr>
					<td>(cough)</td>
					<td>the sound of coughing</td>
				</tr>
				<tr>
					<td>(hum)</td>
					<td>humming (all of <em>hum</em>, <em>erm</em>, <em>ehm hmm</em> 
							etc.)</td>
				</tr>
				<tr>
					<td>(laugh)</td>
					<td>laughter</td>
				</tr>
				<tr>
					<td>(noise)</td>
					<td>noise on the background</td>
				</tr>
				<tr>
					<td>(sil)</td>
					<td>silence if it is prominent or if there is nothing else to transcribe</td>
				</tr>
				<tr>
					<td>(unint)</td>
					<td>unintelligible speech</td>
				</tr>
			</table>

			<h3>Local Names</h3>
			<p>
			The following table lists the correct spelling of some place names 
			that could otherwise be problematic to transcribe:
			</p>
			<div class="quote">
				<table class="booktabs noheader">
					<tr><td>Addenbrooke's</td>		 <td>Girton</td>			<td>Chesterton</td></tr>
					<tr><td>Gonville and Caius</td><td>Castlehill</td>	<td>Romsey</td></tr>
					<tr><td>Barnwell</td>					 <td>Huntingdon</td>	<td>Coco</td></tr>
					<tr><td>Fen Ditton</td>				 <td>Cherryhinton</td><td>Trumpington</td></tr>
					<tr><td>Brasserie</td>				 <td>Newnham</td>			<td></td></tr>
				</table>
			</div>

			<p>
			Please, <strong>DO NOT SPAM</strong>. We will check the responses, 
			and reject all responses from spammers.
			</p>
		</div>
	</div>
	
	<div id="dg">
		<h2>The dialogue</h2>
		<div>
		<form action="" method="POST" id="phases" class="accordion">
			{{ form.non_field_errors }}
			{% csrf_token %}
			{{ form.cid }}
		{% for turn in turns %}
			<h3 id="turn_{{ turn.turn_number }}" class="head ui-state-disabled">
				<a href="#">Turn {{ turn.turn_number }}</a>
			</h3>
			<div>
				<div class="speaker">
					Computer:
				</div>
				<p class="system">{{ turn.prompt }}</p>
			{% if turn.has_rec %}
				<div class="speaker">
					Human:
				</div>
				<div>
					<button type="button" id="btnnext{{ turn.turn_number }}" class="btnnext"
						tabindex="{{ turn.dbl_turn_num|add:1 }}"
						onclick="play_now('btnnext{{ turn.turn_number }}', 'turn_{{ turn.turn_number }}','/apps/transcription/data/recs{{ turn.rec }}');">Play</button>
				</div>
				<div>
					<textarea cols="60" rows="2" style="width: 90%; max-width: 60em;"
						id="id_trs_{{ turn.turn_number }}" name="trs_{{ turn.turn_number }}"
						tabindex="{{ turn.dbl_turn_num|add:2 }}"></textarea>
				</div>
			{% else %}
				<div>
					<button type="button" class="btnnext{{ turn.turn_number }}" 
						tabindex="{{ turn.dbl_turn_num|add:1 }}"
					 onclick="pseudo_play_now('btnnext{{ turn.turn_number }}', 'turn_{{ turn.turn_number }}', '');" class="btnnext">Next</button>
				</div>
			{% endif %}
			
			</div>
		{% endfor %}
	
			<h3 id="phase_answer" class="head ui-state-disabled">
				<a href="#">Submit</a>
			</h3>
			<div>
				<table>
					<tr>
						<td>What was the quality of the recording?</td>
						<td>
							<input id="id_quality_noisy" name="quality" type="radio" 
								value="noisy">
									noisy</input>
						</td>
						<td>
							<input id="id_quality_clear" name="quality" type="radio" 
								value="clear" checked
								tabindex="{{ dbl_num_turns|add:1 }}">
									clear</input>
						</td>
					</tr>
					<tr>
						<td>What accent did the speaker have?</td>
						<td>
							<input id="id_accent_native" name="accent" type="radio" 
								value="native" checked
								tabindex="{{ dbl_num_turns|add:2 }}">
									native English</input>
						</td>
						<td>
							<input id="id_accent_other" name="accent" type="radio" 
							value="other">other</input>
						</td>
					</tr>
					<tr id="accent_spec">
						<td>
							<label for="id_accent_name">What accent did you hear?</label>
						</td>
						<td>
							<input type="text" id="id_accent_name" name="accent_name" 
								size="30"
								tabindex="{{ dbl_num_turns|add:3 }}">
						</td>
					</tr>
					<tr>
						<td>Was offensive language used in the dialogue?</td>
						<td>
							<input id="id_offensive_yes" name="offensive" type="radio" 
								value="yes">
									yes</input>
						</td>
						<td>
							<input id="id_offensive_no" name="offensive" type="radio" 
							value="no" checked
								tabindex="{{ dbl_num_turns|add:4 }}">no</input>
						</td>
					</tr>
					<tr>
						<td colspan="3">
							<label for="id_notes">Should you have any other comments to the dialogue, you can write them down to the box below:</label>
						</td>
					</tr>
					<tr>
						<td colspan="3">
							<textarea id="id_notes" name="notes" cols="50" rows="3"></textarea>
						</td>
					</tr>
					<tr>
						<td colspan="3">
							<input id="submit" type="submit" name="send" value="Save transcription"
											tabindex="{{ dbl_num_turns|add:5 }}">
						</td>
					</tr>
				</table>
			</div>
		</form>
		</div>
	</div>	<!-- end div id="rg" -->
</span>

{% if form.errors %}
<script>
$(document).ready(function() {
$(".ui-state-disabled").removeClass("ui-state-disabled");
$("#phase_answer").click();
});
</script>
{% endif %}

<div id="player">
</div>
{% endblock content %}